export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const INCREASE_ASYNC = 'INCREASE_ASYNC';
